/**
 * BalanceManagementPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.xius.msp.billing.client.balanceManagement;

public interface BalanceManagementPortType extends java.rmi.Remote {
    public com.xius.msp.billing.messages.balanceManagement.GetSubsDetailsResponse getSubsDetails(com.xius.msp.billing.messages.balanceManagement.GetSubsDetailsRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.DoRechargeResponse doRecharge(com.xius.msp.billing.messages.balanceManagement.DoRechargeRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.UpdatePostPaidDiscountResponse updatePostPaidDiscount(com.xius.msp.billing.messages.balanceManagement.UpdatePostPaidDiscountRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.MultiBalAdjustmentResponse multiBalAdjustment(com.xius.msp.billing.messages.balanceManagement.MultiBalAdjustmentRequest multiBalAdjustmentRequest) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.BulkBalAdjustmentResponse bulkBalAdjustment(com.xius.msp.billing.messages.balanceManagement.BulkBalAdjustmentRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.GetAvailableDenomsResponse getAvailableDenoms(com.xius.msp.billing.messages.balanceManagement.GetAvailableDenomsRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.RetrieveVoucherResponse retrieveVoucher(com.xius.msp.billing.messages.balanceManagement.RetrieveVoucherRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.SpecialDebitResponse specialDebit(com.xius.msp.billing.messages.balanceManagement.SpecialDebitRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.RechargeDetailsResponse rechargeDetails(com.xius.msp.billing.messages.balanceManagement.RechargeDetailsRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.SpecialTopUpResponse specialTopUp(com.xius.msp.billing.messages.balanceManagement.SpecialTopUpRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.TransferBalanceResponse transferBalance(com.xius.msp.billing.messages.balanceManagement.TransferBalanceRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.DebitResponse debit(com.xius.msp.billing.messages.balanceManagement.DebitRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.WaiverResponse waiver(com.xius.msp.billing.messages.balanceManagement.WaiverRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.TopUpResponse topUp(com.xius.msp.billing.messages.balanceManagement.TopUpRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.RechargeResponse recharge(com.xius.msp.billing.messages.balanceManagement.RechargeRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.RechargeReversalResponse rechargeReversal(com.xius.msp.billing.messages.balanceManagement.RechargeReversalRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.RechargeInquiryResponse rechargeInquiry(com.xius.msp.billing.messages.balanceManagement.RechargeInquiryRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.GetAllBalancesResponse getAllBalances(com.xius.msp.billing.messages.balanceManagement.GetAllBalancesRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.DebitFullOrPartialCoreBalResponse debitFullOrPartialCoreBal(com.xius.msp.billing.messages.balanceManagement.DebitFullOrPartialCoreBalRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.GetAllBalanceC1Response getAllBalanceC1(com.xius.msp.billing.messages.balanceManagement.GetAllBalanceC1Request getAllBalanceC1Request) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.RechargeStatusUpdResponse rechargeStatusUpd(com.xius.msp.billing.messages.balanceManagement.RechargeStatusUpdRequest rechargeStatusUpdRequest) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.GetRcProductResponse getRcProduct(com.xius.msp.billing.messages.balanceManagement.GetRcProductRequest getRcProductRequest) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.GetMDNRcProductResponse getMDNRcProduct(com.xius.msp.billing.messages.balanceManagement.GetMDNRcProductRequest getMDNRcProductRequest) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.GetRechargeInfoResponse getRechargeInfo(com.xius.msp.billing.messages.balanceManagement.GetRechargeInfoRequest getRechargeInfoRequest) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.GetCategoryListResponse getCategoryList(com.xius.msp.billing.messages.balanceManagement.GetCategoryListRequest getCategoryListRequest) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.DebitOrCreditOfficeBalResponse debitOrCreditOfficeBal(com.xius.msp.billing.messages.balanceManagement.DebitOrCreditOfficeBalRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.UpdateEventAccumlatorResponse updateEventAccumlator(com.xius.msp.billing.messages.balanceManagement.UpdateEventAccumlatorRequest updateEventAccumlatorRequest) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.GetAtpWalletAmountResponse getAtpWalletAmount(com.xius.msp.billing.messages.balanceManagement.GetAtpWalletAmountRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.RcInquiryResponse RCInquiry(com.xius.msp.billing.messages.balanceManagement.RcInquiryRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.IssueLoanResponse issueLoan(com.xius.msp.billing.messages.balanceManagement.IssueLoanRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.balanceManagement.RCRemoveResponse RCRemove(com.xius.msp.billing.messages.balanceManagement.RCRemoveRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
}
