/**
 * AccountManagementPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.xius.msp.billing.client.accountManagement;

public interface AccountManagementPortType extends java.rmi.Remote {
    public com.xius.msp.billing.messages.accountManagement.GetTechnologyResponse getTechnology(com.xius.msp.billing.messages.accountManagement.GetTechnologyRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ValidateSimResponse validateSim(com.xius.msp.billing.messages.accountManagement.ValidateSimRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ValidateMSISDNResponse validateMSISDN(com.xius.msp.billing.messages.accountManagement.ValidateMSISDNRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ReActivateMSISDNResponse reActivateMSISDN(com.xius.msp.billing.messages.accountManagement.ReActivateMSISDNRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetCreditProfilesResponse getCreditProfiles(com.xius.msp.billing.messages.accountManagement.GetCreditProfilesRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.UpdateBillingTypeResponse updateBillingType(com.xius.msp.billing.messages.accountManagement.UpdateBillingTypeRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ViewTroubleTktsResponse viewTroubleTkts(com.xius.msp.billing.messages.accountManagement.ViewTroubleTktsRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ManageTroubleTktsResponse manageTroubleTkts(com.xius.msp.billing.messages.accountManagement.ManageTroubleTktsRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.TrblTktsPreInfoResponse getTroubleTktsPreInfo(com.xius.msp.billing.messages.accountManagement.TrblTktsPreInfoRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ChangeMSISDNsResponse changeMSISDNs(com.xius.msp.billing.messages.accountManagement.ChangeMSISDNsRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.SIMRegistrationResponse simRegistration(com.xius.msp.billing.messages.accountManagement.SIMRegistrationRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.UpdateActDataResponse updateActData(com.xius.msp.billing.messages.accountManagement.UpdateActDataRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.UpdateActStatusResponse updateActStatus(com.xius.msp.billing.messages.accountManagement.UpdateActStatusRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ChangeMSISDNResponse changeMSISDN(com.xius.msp.billing.messages.accountManagement.ChangeMSISDNRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.SIMSwapResponse swapSIM(com.xius.msp.billing.messages.accountManagement.SIMSwapRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ChangeIMSIResponse changeIMSI(com.xius.msp.billing.messages.accountManagement.ChangeIMSIRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ChangeIMSIPreInfoResponse changeIMSIPreInfo(com.xius.msp.billing.messages.accountManagement.ChangeIMSIPreInfoRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.DeActivateAccountResponse deActivateAccount(com.xius.msp.billing.messages.accountManagement.DeActivateAccountRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ChngMSISDNPreInfoResponse changeMSISDNPreInfo(com.xius.msp.billing.messages.accountManagement.ChngMSISDNPreInfoRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetMSISDNInfoResponse getMSISDNInfo(com.xius.msp.billing.messages.accountManagement.GetMSISDNInfoRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.SubGroupChangePreInfoResponse subGroupChangePreInfo(com.xius.msp.billing.messages.accountManagement.SubGroupChangePreInfoRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.SubGroupChangeResponse subGroupChange(com.xius.msp.billing.messages.accountManagement.SubGroupChangeRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ManageAdditionalServicesResponse manageAdditionalServices(com.xius.msp.billing.messages.accountManagement.ManageAdditionalServicesRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetAdditionalServicesResponse getAdditionalServices(com.xius.msp.billing.messages.accountManagement.GetAdditionalServicesRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ConvertAccountTypeResponse convertAccountType(com.xius.msp.billing.messages.accountManagement.ConvertAccountTypeRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetPostpaidAcctDetResponse getPostpaidAcctDet(com.xius.msp.billing.messages.accountManagement.GetPostpaidAcctDetRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.UpdateCreditLimitResponse updateCreditLimit(com.xius.msp.billing.messages.accountManagement.UpdateCreditLimitRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ValidateUserAPIResponse validateUserAPI(com.xius.msp.billing.messages.accountManagement.ValidateUserAPIRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ManageProvsngRetryResponse manageProvsngRetry(com.xius.msp.billing.messages.accountManagement.ManageProvsngRetryRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetAndBlockMSISDNResponse getAndBlockMSISDN(com.xius.msp.billing.messages.accountManagement.GetAndBlockMSISDNRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ChangeSimMdnAuditResponse changeSimMdnAudit(com.xius.msp.billing.messages.accountManagement.ChangeSimMdnAuditRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.SimDealerValidationResponse simDealerValidation(com.xius.msp.billing.messages.accountManagement.SimDealerValidationRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetChargeInfoResponse getChargeInfo(com.xius.msp.billing.messages.accountManagement.GetChargeInfoRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.SimSwapCrdtRptUpdtResponse simSwapCrdtRptUpdt(com.xius.msp.billing.messages.accountManagement.SimSwapCrdtRptUpdtRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.UpdatePostpaidAcctDetResponse updatePostpaidAcctDet(com.xius.msp.billing.messages.accountManagement.UpdatePostpaidAcctDetRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetLocationAssoMsisdnResponse getLocationAssoMsisdn(com.xius.msp.billing.messages.accountManagement.GetLocationAssoMsisdnRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ActivateSubscriberResponse activateSubscriber(com.xius.msp.billing.messages.accountManagement.ActivateSubscriberRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ForceRenewalResponse forceRenewal(com.xius.msp.billing.messages.accountManagement.ForceRenewalRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.HLRIntegrationResponse HLRIntegration(com.xius.msp.billing.messages.accountManagement.HLRIntegrationRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.HLRIntegrationUpdateResponse HLRIntegrationUpdate(com.xius.msp.billing.messages.accountManagement.HLRIntegrationUpdateRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.MDNBasedGetNwIdResponse MDNbasedGetNwId(com.xius.msp.billing.messages.accountManagement.MDNBasedGetNwIdRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.RegSimSwapResponse regSimSwap(com.xius.msp.billing.messages.accountManagement.RegSimSwapRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.UpdateTroubleTktResponse updateTroubleTkt(com.xius.msp.billing.messages.accountManagement.UpdateTroubleTktRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.UpdateSubscriberCategoryResponse updateSubscriberCategory(com.xius.msp.billing.messages.accountManagement.UpdateSubscriberCategoryRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetTroubleTktStatusResponse getTroubleTktStatus(com.xius.msp.billing.messages.accountManagement.GetTroubleTktStatusRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetTroubleTktHistoryResponse getTroubleTktHistory(com.xius.msp.billing.messages.accountManagement.GetTroubleTktHistoryRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.RoamingServiceStatusUpdateResponse roamingServiceStatusUpdate(com.xius.msp.billing.messages.accountManagement.RoamingServiceStatusUpdateRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetAccountDatesResponse getAccountDates(com.xius.msp.billing.messages.accountManagement.GetAccountDatesRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetForceRenDetailsResponse getForceRenDetails(com.xius.msp.billing.messages.accountManagement.GetForceRenDetailsRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetcategoryIDResponse getcategoryID(com.xius.msp.billing.messages.accountManagement.GetcategoryIDRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ManagePathInfoResponse managePathInfo(com.xius.msp.billing.messages.accountManagement.ManagePathInfoRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetPathInfoResponse getPathInfo(com.xius.msp.billing.messages.accountManagement.GetPathInfoRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ValidateIDResponse validateID(com.xius.msp.billing.messages.accountManagement.ValidateIDRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.TeleVerificationResponse teleVerification(com.xius.msp.billing.messages.accountManagement.TeleVerificationRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.ValidateCorpMSISDNVoucherResponse validateCorpMSISDNVoucher(com.xius.msp.billing.messages.accountManagement.ValidateCorpMSISDNVoucherRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.AccountVsBANMappingResponse accountVsBANMapping(com.xius.msp.billing.messages.accountManagement.AccountVsBANMappingRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.PublicityIdHLRcodeGetResponse publicityIdHLRcodeGet(com.xius.msp.billing.messages.accountManagement.PublicityIdHLRcodeGetRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.TtsaUpdateResponse ttsaUpdate(com.xius.msp.billing.messages.accountManagement.TtsaUpdateRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.BascDrvdIdHLRcodeGetResponse bascDrvdIdHLRcodeGet(com.xius.msp.billing.messages.accountManagement.BascDrvdIdHLRcodeGetRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.BascDrvdIdHLRUpdateResponse bascDrvdIdHLRUpdate(com.xius.msp.billing.messages.accountManagement.BascDrvdIdHLRUpdateRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.GetTTPCRFintimateDtlsResponse getTTPCRFintimateDtls(com.xius.msp.billing.messages.accountManagement.GetTTPCRFintimateDtlsRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.TTPCRFUpdateResponse TTPCRFUpdate(com.xius.msp.billing.messages.accountManagement.TTPCRFUpdateRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.CorpTpProdGetUpdateResponse corpTpProdGetUpdate(com.xius.msp.billing.messages.accountManagement.CorpTpProdGetUpdateRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.AccountProductIdMapResponse accountProductIdMap(com.xius.msp.billing.messages.accountManagement.AccountProductIdMapRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
    public com.xius.msp.billing.messages.accountManagement.SimActivateResponse SIMActivate(com.xius.msp.billing.messages.accountManagement.SimActivateRequest body) throws java.rmi.RemoteException, com.xius.msp.billing.messages.common.ErrorDetailsType;
}
