/**
 * SMFManagementPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.xius.agent.smf.SMFManagement_wsdl;

public interface SMFManagementPortType extends java.rmi.Remote {
    public com.xius.agent.smf.SMFManagement_xsd.ActivateTPTrackingResponse activateTPTracking(com.xius.agent.smf.SMFManagement_xsd.ActivateTPTrackingRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.PaymentTransDtlsResponse paymentTransDtls(com.xius.agent.smf.SMFManagement_xsd.PaymentTransDtlsRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.TopUpCUGResponse topUpCUG(com.xius.agent.smf.SMFManagement_xsd.TopUpCUGRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.PersistenceManageResponse persistenceManage(com.xius.agent.smf.SMFManagement_xsd.PersistenceManageRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.SIMActivationResponse SIMActivationInsert(com.xius.agent.smf.SMFManagement_xsd.SIMActivationRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.SIMActivationUpdateResponse SIMActivationUpdate(com.xius.agent.smf.SMFManagement_xsd.SIMActivationUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.SIMSaleResponse SIMSale(com.xius.agent.smf.SMFManagement_xsd.SIMSaleRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.SIMSaleUpdateResponse SIMSaleUpdate(com.xius.agent.smf.SMFManagement_xsd.SIMSaleUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BulkATPSubscriptionUploadResponse bulkATPSubscriptionUpload(com.xius.agent.smf.SMFManagement_xsd.BulkATPSubscriptionUploadRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.ProductPurchageResponse productPurchage(com.xius.agent.smf.SMFManagement_xsd.ProductPurchageRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.ProductPurchaseUpdateResponse productPurchaseUpdate(com.xius.agent.smf.SMFManagement_xsd.ProductPurchaseUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.ViewTransDetailsResponse viewTransDetails(com.xius.agent.smf.SMFManagement_xsd.ViewTransDetailsRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.UploadSimsResponse uploadSims(com.xius.agent.smf.SMFManagement_xsd.UploadSimsRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.GetBulkATPSubsDtlsResponse getBulkATPSubsDtls(com.xius.agent.smf.SMFManagement_xsd.GetBulkATPSubsDtlsRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.SlpnPointsTrackerResponse slpnPointsTracker(com.xius.agent.smf.SMFManagement_xsd.SlpnPointsTrackerRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.SlpnPointsTrackerUpdateResponse slpnPointsTrackerUpdate(com.xius.agent.smf.SMFManagement_xsd.SlpnPointsTrackerUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.DebitTransactionResponse debitTransaction(com.xius.agent.smf.SMFManagement_xsd.DebitTransactionRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.DebitTransactionUpdateResponse debitTransactionUpdate(com.xius.agent.smf.SMFManagement_xsd.DebitTransactionUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.APITrackerResponse APITracker(com.xius.agent.smf.SMFManagement_xsd.APITrackerRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.SimRegistrationResponse simRegistration(com.xius.agent.smf.SMFManagement_xsd.SimRegistrationRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.SimRegistrationUpdateResponse simRegistrationUpdate(com.xius.agent.smf.SMFManagement_xsd.SimRegistrationUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.TransactionTrackerResponse transactionTracker(com.xius.agent.smf.SMFManagement_xsd.TransactionTrackerRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.TransactionTrackerUpdateResponse transactionTrackerUpdate(com.xius.agent.smf.SMFManagement_xsd.TransactionTrackerUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.FirstLUUpdateResponse firstLUUpdate(com.xius.agent.smf.SMFManagement_xsd.FirstLUUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.FirstLUBulkInsertResponse firstLUBulkInsert(com.xius.agent.smf.SMFManagement_xsd.FirstLUBulkInsertRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BucketsSummaryInsertResponse bucketsSummaryInsert(com.xius.agent.smf.SMFManagement_xsd.BucketsSummaryInsertRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BucketsSummaryUpdateResponse bucketsSummaryUpdate(com.xius.agent.smf.SMFManagement_xsd.BucketsSummaryUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BulkTPSubscriptionUploadResponse bulkTPSubscriptionUpload(com.xius.agent.smf.SMFManagement_xsd.BulkTPSubscriptionUploadRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.GetBulkTPSubsDtlsResponse getBulkTPSubsDtls(com.xius.agent.smf.SMFManagement_xsd.GetBulkTPSubsDtlsRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.FirstLuRtryUpdResponse firstLuRtryUpd(com.xius.agent.smf.SMFManagement_xsd.FirstLuRtryUpdRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.LoginLogoutTrackingResponse loginLogoutTracking(com.xius.agent.smf.SMFManagement_xsd.LoginLogoutTrackingRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BulkTPChangeUpdateResponse bulkTPChangeUpdate(com.xius.agent.smf.SMFManagement_xsd.BulkTPChangeUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BulkATPSubscriptionUpdateResponse bulkATPSubscriptionUpdate(com.xius.agent.smf.SMFManagement_xsd.BulkATPSubscriptionUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.ChangeTPResponse changeTP(com.xius.agent.smf.SMFManagement_xsd.ChangeTPRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.ATPSubscriptionResponse ATPSubscription(com.xius.agent.smf.SMFManagement_xsd.ATPSubscriptionRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.GenerateTokenResponse generateToken(com.xius.agent.smf.SMFManagement_xsd.GenerateTokenRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.ValidateTokenResponse validateToken(com.xius.agent.smf.SMFManagement_xsd.ValidateTokenRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.ManageProvsngRetryResponse manageProvsngRetry(com.xius.agent.smf.SMFManagement_xsd.ManageProvsngRetryRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.PaymentInsertResponse paymentInsert(com.xius.agent.smf.SMFManagement_xsd.PaymentInsertRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.PaymentUpdateResponse paymentUpdate(com.xius.agent.smf.SMFManagement_xsd.PaymentUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.PaymentTransReportResponse paymentTransReport(com.xius.agent.smf.SMFManagement_xsd.PaymentTransReportRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BulkSpecialCreditUpldResponse bulkSpecialCreditUpld(com.xius.agent.smf.SMFManagement_xsd.BulkSpecialCreditUpldRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BulkDebitUpldResponse bulkDebitUpld(com.xius.agent.smf.SMFManagement_xsd.BulkDebitUpldRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BulkCreditUpldResponse bulkCreditUpld(com.xius.agent.smf.SMFManagement_xsd.BulkCreditUpldRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.GetBulkCreditTransDtlsResponse getBulkCreditTransDtls(com.xius.agent.smf.SMFManagement_xsd.GetBulkCreditTransDtlsRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.GetBulkSplCreditTransDtlsResponse getBulkSplCreditTransDtls(com.xius.agent.smf.SMFManagement_xsd.GetBulkSplCreditTransDtlsRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.GetBulkDebitTransDtlsResponse getBulkDebitTransDtls(com.xius.agent.smf.SMFManagement_xsd.GetBulkDebitTransDtlsRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.UpdatePersonalDetailsInsertResponse updatePersonalDetailsInsert(com.xius.agent.smf.SMFManagement_xsd.UpdatePersonalDetailsInsertRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.UpdtPrsnlDtlsUpdateResponse updtPrsnlDtlsUpdate(com.xius.agent.smf.SMFManagement_xsd.UpdtPrsnlDtlsUpdateRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BlkCorpActDeActInsertResponse blkCorpActDeActInsert(com.xius.agent.smf.SMFManagement_xsd.BlkCorpActDeActInsertRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.BlkCorpRCInsertResponse blkCorpRCInsert(com.xius.agent.smf.SMFManagement_xsd.BlkCorpRCInsertRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.agent.smf.SMFManagement_xsd.GetBalanceTransStatusResponse getBalanceTransStatus(com.xius.agent.smf.SMFManagement_xsd.GetBalanceTransStatusRequest body) throws java.rmi.RemoteException, com.xius.agent.smf.common.error.ErrorDetails_xsd.ErrorDetailsType;
}
