/**
 * SubscriberManagementPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.xius.msp.billing.client.SubscriberManagement;

public interface SubscriberManagementPortType extends java.rmi.Remote {
    public com.xius.msp.billing.messages.SubscriberManagement.ManageBannerResponse manageBanner(com.xius.msp.billing.messages.SubscriberManagement.ManageBannerRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetbalanceInfoResponse getBalanceInfo(com.xius.msp.billing.messages.SubscriberManagement.GetbalanceInfoRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetBundlesDetailsResponse getBundlesDetails(com.xius.msp.billing.messages.SubscriberManagement.GetBundlesDetailsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetPromoDetailsResponse getPromoDetails(com.xius.msp.billing.messages.SubscriberManagement.GetPromoDetailsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.UpdatePromoStatusResponse updatePromoStatus(com.xius.msp.billing.messages.SubscriberManagement.UpdatePromoStatusRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ManagePromoResponse managePromo(com.xius.msp.billing.messages.SubscriberManagement.ManagePromoRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetFnFSMSResponse getFnFSMS(com.xius.msp.billing.messages.SubscriberManagement.GetFnFSMSRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetBundlesResponse getBundles(com.xius.msp.billing.messages.SubscriberManagement.GetBundlesRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetBucketsResponse getBuckets(com.xius.msp.billing.messages.SubscriberManagement.GetBucketsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetSubViewDataResponse getSubViewData(com.xius.msp.billing.messages.SubscriberManagement.GetSubViewDataRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ManageFnFSMSResponse manageFnFSMS(com.xius.msp.billing.messages.SubscriberManagement.ManageFnFSMSRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ChangeLanguagePreInfoResponse changeLanguagePreInfo(com.xius.msp.billing.messages.SubscriberManagement.ChangeLanguagePreInfoRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ChangeLanguageResponse changeLanguage(com.xius.msp.billing.messages.SubscriberManagement.ChangeLanguageRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetNPANXXResponse getNPANXX(com.xius.msp.billing.messages.SubscriberManagement.GetNPANXXRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetNPANXXForExResponse getNPANXXForEx(com.xius.msp.billing.messages.SubscriberManagement.GetNPANXXForExRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetSubscriberInfoResponse getSubscriberInfo(com.xius.msp.billing.messages.SubscriberManagement.GetSubscriberInfoRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ManageBundleResponse manageBundle(com.xius.msp.billing.messages.SubscriberManagement.ManageBundleRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.SubscribeOptionalServicesResponse subscribeOptionalServices(com.xius.msp.billing.messages.SubscriberManagement.SubscribeOptionalServicesRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ConfigureServicesResponse configureServices(com.xius.msp.billing.messages.SubscriberManagement.ConfigureServicesRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ChangeTariffPlanPreInfoResponse changeTariffPlanPreInfo(com.xius.msp.billing.messages.SubscriberManagement.ChangeTariffPlanPreInfoRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ChangeTariffPlanResponse changeTariffPlan(com.xius.msp.billing.messages.SubscriberManagement.ChangeTariffPlanRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.SubOptServicesPreInfoResponse subOptServicesPreInfo(com.xius.msp.billing.messages.SubscriberManagement.SubOptServicesPreInfoRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.PUKDetailsResponse PUKDetails(com.xius.msp.billing.messages.SubscriberManagement.PUKDetailsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetNotesResponse getNotes(com.xius.msp.billing.messages.SubscriberManagement.GetNotesRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.AddNoteResponse addNote(com.xius.msp.billing.messages.SubscriberManagement.AddNoteRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ManageNoteResponse manageNote(com.xius.msp.billing.messages.SubscriberManagement.ManageNoteRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetAssocMSISDNResponse getAssociatedMSISDNs(com.xius.msp.billing.messages.SubscriberManagement.GetAssocMSISDNRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetAccountSummaryResponse getAccountSummary(com.xius.msp.billing.messages.SubscriberManagement.GetAccountSummaryRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetDeviceInfoResponse getDeviceInfo(com.xius.msp.billing.messages.SubscriberManagement.GetDeviceInfoRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.UpdateDeviceInfoResponse updateDeviceInfo(com.xius.msp.billing.messages.SubscriberManagement.UpdateDeviceInfoRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetBalanceDetailsResponse getBalanceDetails(com.xius.msp.billing.messages.SubscriberManagement.GetBalanceDetailsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetBannerResponse getBanner(com.xius.msp.billing.messages.SubscriberManagement.GetBannerRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetDataPlansResponse getDataPlans(com.xius.msp.billing.messages.SubscriberManagement.GetDataPlansRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ManageDataPlansResponse manageDataPlans(com.xius.msp.billing.messages.SubscriberManagement.ManageDataPlansRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetSessionStatusResponse getSessionStatus(com.xius.msp.billing.messages.SubscriberManagement.GetSessionStatusRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetSubDataPlansResponse getSubDataPlans(com.xius.msp.billing.messages.SubscriberManagement.GetSubDataPlansRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.InsertNotificationResponse insertNotification(com.xius.msp.billing.messages.SubscriberManagement.InsertNotificationRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.AddnlServicePlanPreInfoResponse addnlServicePlanPreInfo(com.xius.msp.billing.messages.SubscriberManagement.AddnlServicePlanPreInfoRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ChangeAddnlServicePlanResponse changeAddnlServicePlan(com.xius.msp.billing.messages.SubscriberManagement.ChangeAddnlServicePlanRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetBndlBucketsResponse getBndlBuckets(com.xius.msp.billing.messages.SubscriberManagement.GetBndlBucketsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetTariffServicePackDtlsResponse getTariffServicePackDtls(com.xius.msp.billing.messages.SubscriberManagement.GetTariffServicePackDtlsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetBundleDtlsResponse getBundleDtls(com.xius.msp.billing.messages.SubscriberManagement.GetBundleDtlsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetBaseSubsServicesResponse getBaseSubsServices(com.xius.msp.billing.messages.SubscriberManagement.GetBaseSubsServicesRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetBaseATPServicesResponse getBaseATPServices(com.xius.msp.billing.messages.SubscriberManagement.GetBaseATPServicesRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ServiceDeleteResponse serviceDelete(com.xius.msp.billing.messages.SubscriberManagement.ServiceDeleteRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetMSISDNTypeResponse getMSISDNType(com.xius.msp.billing.messages.SubscriberManagement.GetMSISDNTypeRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetNotificationDataResponse getNotificationData(com.xius.msp.billing.messages.SubscriberManagement.GetNotificationDataRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.UpdateNotificationDataResponse updateNotificationData(com.xius.msp.billing.messages.SubscriberManagement.UpdateNotificationDataRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetSubDataResponse getSubData(com.xius.msp.billing.messages.SubscriberManagement.GetSubDataRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.AppendBulkIMSIsResponse appendBulkIMSIs(com.xius.msp.billing.messages.SubscriberManagement.AppendBulkIMSIsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.SubscriberValidationResponse subscriberValidation(com.xius.msp.billing.messages.SubscriberManagement.SubscriberValidationRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetTariffPackageResponse getTariffPackage(com.xius.msp.billing.messages.SubscriberManagement.GetTariffPackageRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.BundlePurchaseResponse bundlePurchase(com.xius.msp.billing.messages.SubscriberManagement.BundlePurchaseRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetPublicityIdDetailsResponse getPublicityIdDetails(com.xius.msp.billing.messages.SubscriberManagement.GetPublicityIdDetailsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.SetInitialBalanceResponse setInitialBalance(com.xius.msp.billing.messages.SubscriberManagement.SetInitialBalanceRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetAttachedPackagesResponse getAttachedPackages(com.xius.msp.billing.messages.SubscriberManagement.GetAttachedPackagesRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.CancelAccountResponse cancelAccount(com.xius.msp.billing.messages.SubscriberManagement.CancelAccountRequest request) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.ActiveBucketSummaryResponse activeBucketSummary(com.xius.msp.billing.messages.SubscriberManagement.ActiveBucketSummaryRequest request) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetMultiplePublicityIdDtlsResponse getMultiplePublicityIdDtls(com.xius.msp.billing.messages.SubscriberManagement.GetMultiplePublicityIdDtlsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.PostPaidPreInfoResponse postPaidPreInfo(com.xius.msp.billing.messages.SubscriberManagement.PostPaidPreInfoRequest request) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetTPActivationFeeResponse getTPActivationFee(com.xius.msp.billing.messages.SubscriberManagement.GetTPActivationFeeRequest request) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetFreeMDNSResponse getFreeMDNS(com.xius.msp.billing.messages.SubscriberManagement.GetFreeMDNSRequest request) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.UpdateSubsIDResponse updateSubsID(com.xius.msp.billing.messages.SubscriberManagement.UpdateSubsIDRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetAccntsCountOfIDResponse getAccntsCountOfID(com.xius.msp.billing.messages.SubscriberManagement.GetAccntsCountOfIDRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetMsisdnbasedATPDtlsResponse getMsisdnbasedATPDtls(com.xius.msp.billing.messages.SubscriberManagement.GetMsisdnbasedATPDtlsRequest request) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.CheckCommercialTPResponse checkCommercialTP(com.xius.msp.billing.messages.SubscriberManagement.CheckCommercialTPRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetMsisdnAttachedATPDtlsResponse getMsisdnAttachedATPDtls(com.xius.msp.billing.messages.SubscriberManagement.GetMsisdnAttachedATPDtlsRequest request) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetNIRResponse getNIR(com.xius.msp.billing.messages.SubscriberManagement.GetNIRRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetOfficeNIRResponse getOfficeNIR(com.xius.msp.billing.messages.SubscriberManagement.GetOfficeNIRRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetsubBaseServicesttResponse getsubBaseServicestt(com.xius.msp.billing.messages.SubscriberManagement.GetsubBaseServicesttRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetMulBndlNameDetailsResponse getMulBndlNameDetails(com.xius.msp.billing.messages.SubscriberManagement.GetMulBndlNameDetailsRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetRCPreInfoResponse getRCPreInfo(com.xius.msp.billing.messages.SubscriberManagement.GetRCPreInfoRequest request) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetETNotifInfoResponse getETNotifInfo(com.xius.msp.billing.messages.SubscriberManagement.GetETNotifInfoRequest request) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetChngeTpRecquiredResponse getChngeTpRecquired(com.xius.msp.billing.messages.SubscriberManagement.GetChngeTpRecquiredRequest request) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
    public com.xius.msp.billing.messages.SubscriberManagement.GetCommercialSimFlagResponse getCommercialSimFlag(com.xius.msp.billing.messages.SubscriberManagement.GetCommercialSimFlagRequest body) throws java.rmi.RemoteException, com.xius.billing.common.error.ErrorDetails_xsd.ErrorDetailsType;
}
